### ISSUE TITLE
Composer doesn't pull into the correct place.

### ISSUE THREAD

**Issue by ryanwelcher** [10up/wp-content-connect#25]
When trying to pull this into a project, the plugin is always installed in  a `10up` directory inside the plugins folder. Which doesn't work with the installer-path setup for other wordpress-plugins.

```
"installer-paths": {
      "plugins/{$name}/": ["type:wordpress-plugin" ]
}
```

**Comment by cmmarslender** [comment]
The thought for having this as a "library" rather than a plugin is that it doesn't really do much on its own - you have to define relationships and such for this to be useful. With this in mind, having this loaded as a dependency of a plugin or theme that defines the relationships is more along the lines of how its set up now.

**Comment by jeffpaul** [comment]
So maybe that's something we should add to the docs in the readme instead?

**Comment by moraleida** [comment]
Documentation was improved in #39 with installation instructions for library and plugin use-cases
